blank_issues_enabled: false
contact_links:
  - name: Support & Discussion
    url: https://discord.com/channels/1103598609804562463/1357634772666552340
    about: Ask questions and get help from the community on Discord.
