# Auto-generated test discovery for JUCE unit tests.

if(NOT DEFINED TEST_BINARY)
    message(FATAL_ERROR "DiscoverJuceTests.cmake: TEST_BINARY variable not set")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "DiscoverJuceTests.cmake: OUTPUT_FILE variable not set")
endif()

if(NOT EXISTS "${TEST_BINARY}")
    message(FATAL_ERROR "DiscoverJuceTests.cmake: Test binary '${TEST_BINARY}' does not exist")
endif()

execute_process(
    COMMAND "${TEST_BINARY}" --list-tests
    RESULT_VARIABLE discovery_result
    OUTPUT_VARIABLE discovery_output
    ERROR_VARIABLE discovery_error
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE
)

if(NOT discovery_result EQUAL 0)
    message(FATAL_ERROR
        "DiscoverJuceTests.cmake: Failed to list tests from '${TEST_BINARY}' "
        "(exit code ${discovery_result}). STDERR:\n${discovery_error}")
endif()

file(WRITE "${OUTPUT_FILE}"
    "# This file is auto-generated by cmake/DiscoverJuceTests.cmake. Do not edit.\n")

string(REGEX MATCHALL "TEST:[^\r\n]+" discovered_lines "${discovery_output}")

if(discovered_lines)
    foreach(test_line IN LISTS discovered_lines)
        string(REGEX REPLACE "^TEST:" "" test_name "${test_line}")
        string(STRIP "${test_name}" test_name)
        if(test_name STREQUAL "")
            continue()
        endif()

        string(REPLACE "\"" "\\\"" escaped_test_name "${test_name}")

        file(APPEND "${OUTPUT_FILE}"
            "add_test(\"${escaped_test_name}\" \"${TEST_BINARY}\" \"${escaped_test_name}\")\n")
    endforeach()
else()
    file(APPEND "${OUTPUT_FILE}" "# No JUCE tests discovered in '${TEST_BINARY}'.\n")
endif()
